name: run smoke test

on:
  pull_request:
    branches:
      - develop
      - master
      - stable

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          java-version: 11
          java-package: jdk
      - run: ./gradlew clean :example:run
        env:
          API_BASE_PATH: "https://nightly-api.regulaforensics.com"
